# Connection settings for ComfyV
server_address: "https://tensorboard-nefrqcy3dr.clg07azjl.paperspacegradient.com"
# api_key: "your-secret-api-key" # 
#アンジュの8以外奈良かの全部を股やろうと考えてるかプロンプト考えて。アンジュの1,2はそんな激しい動きイラン
#  。はーはーしてるくらい。3は自分でお尻広げてみせる。4は腰を主に動かして胸は自分で揉んでる。5,6はそのまま
#  。奈良かのやつは5がせいえきたれてるかんじで。アンジュの7は複数パターン、目だけつぶって手でしこしこしたり
#  、喉奥まで加えたり、ペースを早くしたり、1ストロークでねっとりしたり。　考えるだけまだ投入しない